name: Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Change to 3.11 or 3.10

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-distutils  # Install distutils
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Streamlit
      run: streamlit run next_module_attendance_ratio_super_batch_level.py  # Replace with your main script name
