name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Replace with the Python version you're using

    - name: Check Python version
      run: python3.9 --version

    - name: Check enabled repositories
      run: |
        sudo apt-get update
        apt-cache policy

    - name: Enable universe repository
      run: |
        sudo add-apt-repository universe
        sudo apt-get update

    - name: Install dependencies
      run: |
        # sudo apt-get update
        # sudo apt-get install python3-distutils -y  # Installs distutils
        sudo apt-get update
        sudo apt-get install python3.9-distutils -y
        #python -m 
        pip install --upgrade pip
        # pip install scikit-learn==1.0.2 --prefer-binary
        pip install -r requirements.txt
    
   # - name: Run Streamlit
   #   run: streamlit run next_module_attendance_ratio_super_batch_level.py

    - name: Run Streamlit
      run: |
        nohup streamlit run next_module_attendance_ratio_super_batch_level.py &
        sleep 5  # Wait for 5 seconds to allow the Streamlit app to start

